### ISSUE TITLE
Doesn't support enough variable types

### ISSUE THREAD

**Issue by porglezomp** [kevinmehall/rust-vcd#2]
I tried to parse a VCD output by a SymbiYosys run, and found that this failed on the `integer` and `event` types.

**Comment by porglezomp** [comment]
Ah, I see that you have most of the code written for this, just some of it is commented out.

**Comment by kevinmehall** [comment]
Want to submit a PR?

It may be as simple as un-commenting these lines and adding them to the `from_str` method just below:
https://github.com/kevinmehall/rust-vcd/blob/b69960dab46c3dcb9644032e4d311f50f97389bd/src/lib.rs#L262-L265

It looks like `integer` gets encoded the same as `wire`, so its changes would be handled by the existing `Command::ChangeVector`. I'm not sure about `event`. Can you post a sample file?

**Comment by porglezomp** [comment]
I'm working on those changes for you right now. It looks like it's also valid to declare variables outside a `$scope`, which might require more changes.

Here's the start of the VCD I'm working with, to see that the `event` is also encoded like a `wire`:
```vcd
$var integer 32 t smt_step $end
$var event 1 ! smt_clock $end
$scope module queue $end
$var wire 8 n11 buffer<0> $end
$var wire 1 n0 i_clk $end
$var wire 8 n1 i_data $end
$var wire 1 n2 i_read_enable $end
$var wire 1 n3 i_reset_n $end
$var wire 1 n4 i_write_enable $end
$var wire 1 n5 matches $end
$var wire 8 n6 o_data $end
$var wire 1 n7 o_empty $end
$var wire 1 n8 o_full $end
$var wire 5 n9 r_ptr $end
$var wire 5 n10 w_ptr $end
$upscope $end
$enddefinitions $end
#0
1!
b00000000000000000000000000000000 t
```

**Comment by porglezomp** [comment]
Does having the header instead store a top-level scope with an empty name sound good to you? I think that would elegantly handle storing top-level `$var` and multiple sibling `$scope` declarations, I'll just need to adjust the parsing to handle it rather than having to restructure the types.

**Comment by porglezomp** [comment]
Alternately, instead of having a top-level scope, would could store `items: Vec<ScopeItem>`, which might be more appropriate.

**Comment by kevinmehall** [comment]
> Alternately, instead of having a top-level scope, would could store items: Vec<ScopeItem>, which might be more appropriate.

:+1: Just what I had started to write a reply suggesting.
