### ISSUE TITLE
The IdCode hashing doesn't avoid collisions

### ISSUE THREAD

**Issue by porglezomp** [kevinmehall/rust-vcd#3]
The most trivial case: `!` and `!!` both map to 0. In fact, `!ident` and `ident` will always map to the same thing for any `ident`.

Changing `i - ID_CHAR_MIN` to `i - ID_CHAR_MIN + 1` would still run into collisions after integer overflow.

**Comment by porglezomp** [comment]
I think the thing to do would be to perform string interning rather than hashing.

**Comment by kevinmehall** [comment]
IIRC, the original spec limits it to 4 characters, so if that's commonly obeyed, it can be encoded in a `u32` (or just a `[u8; 4]`) which is nice because it can be `Copy` and doesn't require global state.

**Comment by porglezomp** [comment]
I suspect it's not commonly obeyed in practice. The results I'm getting with SymbiYosys have variables of the form `n0`, `n1`, etc. so just getting to `n1000` (seems likely on a flattened design) would collide with `n100` if we used `[u8; 4]`.

**Comment by kevinmehall** [comment]
Hmm, well making it a u64 using a correctly implemented dense "base-94" encoding would cover up to n999999999 in that scheme.

**Comment by kevinmehall** [comment]
Implemented that in 613415263bd. I also added overflow checking to reject IDs that are too long.
