### ISSUE TITLE
Doesn't support top-level variables or multiple top-level scopes

### ISSUE THREAD

**Issue by porglezomp** [kevinmehall/rust-vcd#4]
Just splitting this issue off #2 for documentation purposes.

This fails:

```
$var wire 1 ! foo $end
$enddefinitions $end
```

**Comment by porglezomp** [comment]
I've started fixing this in #5.

One API question this opens up: We can't do `header.scope.find_var` anymore. Should we add a method for finding vars in the instances? How should we find vars in nested modules?

**Comment by kevinmehall** [comment]
Yeah, something like `header.find_var(&["top", "clock"])` to find a var by its path in nested modules could be nice to cover that use case.

**Comment by porglezomp** [comment]
I've added `Header::find_scope` and `Header::find_var` in #5

**Comment by kevinmehall** [comment]
Fixed in #5
