### ISSUE TITLE
Variable declaration with bit selection or range produces errors.

### ISSUE THREAD

**Issue by giselher** [kevinmehall/rust-vcd#8]
I get the following error, even though my VCD file is correct. Correct in the sense that gtkwave reads it.
``` Error: Custom { kind: InvalidData, error: StringError("expected $end") } ```

gtkwave is able to process the following line, but rust-vcd is not.
```$var wire 2 a signal [4:0] $end```

Do you plan to support this?
After reading the IEEE spec I am still unsure if the space is valid or not.

**Comment by kevinmehall** [comment]
Is this the same as https://github.com/kevinmehall/rust-vcd/pull/7? Looks like I accepted that PR and then forgot to publish a new version to crates.io.

Can you try the master branch? (`vcd = { git = "https://github.com/kevinmehall/rust-vcd.git" }` in `Cargo.toml`). I'll release a new version or accept a PR to add this.

**Comment by giselher** [comment]
Yes, it is the same as #7  thanks for the quick reply. I will close this ticket.

**Comment by kevinmehall** [comment]
Published 0.5.0
